package Calculadora;

/**
* Calculadora/CalculadoraAppHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculadoraApp.idl
* Quinta-feira, 31 de Agosto de 2017 21h32min13s BRT
*/

public final class CalculadoraAppHolder implements org.omg.CORBA.portable.Streamable
{
  public Calculadora.CalculadoraApp value = null;

  public CalculadoraAppHolder ()
  {
  }

  public CalculadoraAppHolder (Calculadora.CalculadoraApp initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Calculadora.CalculadoraAppHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Calculadora.CalculadoraAppHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Calculadora.CalculadoraAppHelper.type ();
  }

}
