package Calculadora;


/**
* Calculadora/CalculadoraAppPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculadoraApp.idl
* Quinta-feira, 31 de Agosto de 2017 21h32min13s BRT
*/

public abstract class CalculadoraAppPOA extends org.omg.PortableServer.Servant
 implements Calculadora.CalculadoraAppOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("somafn", new java.lang.Integer (0));
    _methods.put ("subtracaofn", new java.lang.Integer (1));
    _methods.put ("multiplicacaofn", new java.lang.Integer (2));
    _methods.put ("divisaofn", new java.lang.Integer (3));
    _methods.put ("potenciafn", new java.lang.Integer (4));
    _methods.put ("raizfn", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Calculadora/CalculadoraApp/somafn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.somafn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // Calculadora/CalculadoraApp/subtracaofn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.subtracaofn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 2:  // Calculadora/CalculadoraApp/multiplicacaofn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.multiplicacaofn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 3:  // Calculadora/CalculadoraApp/divisaofn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.divisaofn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 4:  // Calculadora/CalculadoraApp/potenciafn
       {
         double a = in.read_double ();
         double b = in.read_double ();
         double $result = (double)0;
         $result = this.potenciafn (a, b);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 5:  // Calculadora/CalculadoraApp/raizfn
       {
         double a = in.read_double ();
         double $result = (double)0;
         $result = this.raizfn (a);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Calculadora/CalculadoraApp:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CalculadoraApp _this() 
  {
    return CalculadoraAppHelper.narrow(
    super._this_object());
  }

  public CalculadoraApp _this(org.omg.CORBA.ORB orb) 
  {
    return CalculadoraAppHelper.narrow(
    super._this_object(orb));
  }


} // class CalculadoraAppPOA
