package Calculadora;


/**
* Calculadora/CalculadoraAppOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculadoraApp.idl
* Quinta-feira, 31 de Agosto de 2017 21h32min13s BRT
*/

public interface CalculadoraAppOperations 
{
  double somafn (double a, double b);
  double subtracaofn (double a, double b);
  double multiplicacaofn (double a, double b);
  double divisaofn (double a, double b);
  double potenciafn (double a, double b);
  double raizfn (double a);
} // interface CalculadoraAppOperations
