package Calculadora;


/**
* Calculadora/CalculadoraAppHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculadoraApp.idl
* Quinta-feira, 31 de Agosto de 2017 21h32min13s BRT
*/

abstract public class CalculadoraAppHelper
{
  private static String  _id = "IDL:Calculadora/CalculadoraApp:1.0";

  public static void insert (org.omg.CORBA.Any a, Calculadora.CalculadoraApp that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Calculadora.CalculadoraApp extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Calculadora.CalculadoraAppHelper.id (), "CalculadoraApp");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Calculadora.CalculadoraApp read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalculadoraAppStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Calculadora.CalculadoraApp value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Calculadora.CalculadoraApp narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Calculadora.CalculadoraApp)
      return (Calculadora.CalculadoraApp)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Calculadora._CalculadoraAppStub stub = new Calculadora._CalculadoraAppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Calculadora.CalculadoraApp unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Calculadora.CalculadoraApp)
      return (Calculadora.CalculadoraApp)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Calculadora._CalculadoraAppStub stub = new Calculadora._CalculadoraAppStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
