package Calculadora;


/**
* Calculadora/CalculadoraApp.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CalculadoraApp.idl
* Quinta-feira, 31 de Agosto de 2017 21h32min13s BRT
*/

public interface CalculadoraApp extends CalculadoraAppOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CalculadoraApp
